### ISSUE TITLE
Should we consider adding Imagick as an extension as well?

### ISSUE THREAD

**Issue by BronsonQuick** [Chassis/core_dev#29]
I know WordPress is designed to work without Imagick if it's not installed and if it is installed then it uses all the awesomeness of Imagick.

Should we consider adding `chassis/imagick` as a `core-dev` extension or should we keep it lean and document that we can add that if we need to? I don't really have an opinion either way so I'll let the majority decide.

The new WordPress `Site Health` page throws warnings for `imagick` and `bcmath` but hopefully the later will disappear: https://core.trac.wordpress.org/ticket/47454

**Comment by kadamwhite** [comment]
Since it's not required for core development, I don't want to make it a hard requirement; but I'd be in favor of noting it in the README. Maybe a new "other useful extensions" heading, with a shortlist of the extensions with the most complementary benefit: imagick for speeding up images / permitting better testing of media component work, xdebug for general utility, etc.

**Comment by BronsonQuick** [comment]
Awesome! Great feedback Sir. Thanks for validating my thoughts! 🥰
